site_name: 生信爱好者周刊
docs_dir: "issues"
site_dir: "site"
theme:
  #name: mkdocs
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - navigation.top
repo_url: https://github.com/ShixiangWang/weekly
edit_uri: https://github.com/ShixiangWang/weekly/edit/master/
site_author: Shixiang Wang
copyright: Copyright © 2021-2023 ShixiangWang, kkjtmac, NiEntropy, He-Kai-fly, JnanZhang, Tomcxf, wangdepin and Openbiox community
nav:
    - 阅读说明: README.md
    - 周刊:
      - issue-65.md
      - issue-64.md
      - issue-63.md
      - issue-62.md
      - issue-61.md
      - issue-60.md
      - issue-59.md
      - issue-58.md
      - issue-57.md
      - issue-56.md
      - issue-55.md
      - issue-54.md
      - issue-53.md
      - issue-52.md
      - issue-51.md
      - issue-50.md
      - issue-49.md
      - issue-48.md
      - issue-47.md
      - issue-46.md
      - issue-45.md
      - issue-44.md
      - issue-43.md
      - issue-42.md
      - issue-41.md
      - issue-40.md
      - issue-39.md
      - issue-38.md
      - issue-37.md
      - issue-36.md
      - issue-35.md
      - issue-34.md
      - issue-33.md
      - issue-32.md
      - issue-31.md
      - issue-30.md
      - issue-29.md
      - issue-28.md
      - issue-27.md
      - issue-26.md
      - issue-25.md
      - issue-24.md
      - issue-23.md
      - issue-22.md
      - issue-21.md
      - issue-20.md
      - issue-19.md
      - issue-18.md
      - issue-17.md
      - issue-16.md
      - issue-15.md
      - issue-14.md
      - issue-13.md
      - issue-12.md
      - issue-11.md
      - issue-10.md
      - issue-9.md
      - issue-8.md
      - issue-7.md
      - issue-6.md
      - issue-5.md
      - issue-4.md
      - issue-3.md
      - issue-2.md
      - issue-1.md
      
    - 排班表: https://github.com/ShixiangWang/weekly/issues/1352
    - 内容推荐: https://github.com/ShixiangWang/weekly/issues/new?assignees=&labels=%E6%8E%A8%E8%8D%90&template=a-recommand.md&title=%E3%80%90%E6%8E%A8%E8%8D%90%E3%80%91%E5%B0%81%E9%9D%A2%2F%E8%AF%9D%E9%A2%98%2F%E7%94%9F%E4%BF%A1%E7%A0%94%E7%A9%B6%2F%E5%8D%9A%E6%96%87%E8%B5%84%E8%AE%AF%2F%E5%B7%A5%E5%85%B7%2F%E8%B5%84%E6%BA%90%E6%8E%A8%E8%8D%90+%7C+xxx
markdown_extensions:
    - smarty
    - toc:
        permalink: True
        separator: "-"
        toc_depth: 3
